title: Get a Minecraft block ID
hero_image: images/banner.png
description: Fetch a block ID in Minecraft using Python
original_url: 
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 # possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: false
curriculum: 
interests: 
technologies: "minecraft, python"
site_areas:
steps:
  - title: Fetch a block ID

